"""
Expanded Anime + Character Dataset (150 Anime)
Each anime includes top 3-5 main characters for generation
"""

ANIME_CHARACTER_DATA = [
    {"mal_id": 5114, "title": "Fullmetal Alchemist: Brotherhood", "score": 9.09, "rank": 1, "year": 2009, "characters": ["Edward Elric", "Alphonse Elric", "Roy Mustang", "Winry Rockbell", "Riza Hawkeye"]},
    {"mal_id": 9253, "title": "Steins;Gate", "score": 9.07, "rank": 2, "year": 2011, "characters": ["Rintarou Okabe", "Makise Kurisu", "Mayuri Shiina", "Itaru Hashida", "Suzuha Amane"]},
    {"mal_id": 38524, "title": "Shingeki no Kyojin Season 3 Part 2", "score": 9.05, "rank": 3, "year": 2019, "characters": ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman", "Erwin Smith"]},
    {"mal_id": 11061, "title": "Hunter x Hunter (2011)", "score": 9.02, "rank": 4, "year": 2011, "characters": ["Gon Freecss", "Killua Zoldyck", "Kurapika", "Leorio Paradinight", "Hisoka Morow"]},
    {"mal_id": 52991, "title": "Sousou no Frieren", "score": 9.30, "rank": 5, "year": 2023, "characters": ["Frieren", "Fern", "Stark", "Himmel", "Heiter"]},
    {"mal_id": 1535, "title": "Death Note", "score": 8.62, "rank": 6, "year": 2006, "characters": ["Light Yagami", "L Lawliet", "Ryuk", "Misa Amane", "Near"]},
    {"mal_id": 16498, "title": "Shingeki no Kyojin", "score": 8.55, "rank": 7, "year": 2013, "characters": ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman", "Sasha Blouse"]},
    {"mal_id": 28977, "title": "Gintama", "score": 8.96, "rank": 8, "year": 2015, "characters": ["Gintoki Sakata", "Kagura", "Shinpachi Shimura", "Hijikata Toushirou", "Okita Sougo"]},
    {"mal_id": 38000, "title": "Kimetsu no Yaiba", "score": 8.50, "rank": 9, "year": 2019, "characters": ["Tanjiro Kamado", "Nezuko Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Giyu Tomioka"]},
    {"mal_id": 40748, "title": "Jujutsu Kaisen", "score": 8.59, "rank": 10, "year": 2020, "characters": ["Yuji Itadori", "Megumi Fushiguro", "Nobara Kugisaki", "Satoru Gojo", "Sukuna"]},
    {"mal_id": 1, "title": "Cowboy Bebop", "score": 8.75, "rank": 11, "year": 1998, "characters": ["Spike Spiegel", "Jet Black", "Faye Valentine", "Edward Wong", "Ein"]},
    {"mal_id": 21, "title": "One Piece", "score": 8.71, "rank": 12, "year": 1999, "characters": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Sanji", "Tony Tony Chopper"]},
    {"mal_id": 20, "title": "Naruto", "score": 8.00, "rank": 13, "year": 2002, "characters": ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno", "Kakashi Hatake", "Hinata Hyuga"]},
    {"mal_id": 30276, "title": "One Punch Man", "score": 8.49, "rank": 14, "year": 2015, "characters": ["Saitama", "Genos", "Speed-o'-Sound Sonic", "Mumen Rider", "Tatsumaki"]},
    {"mal_id": 31043, "title": "Boku no Hero Academia", "score": 7.86, "rank": 15, "year": 2016, "characters": ["Izuku Midoriya", "Katsuki Bakugo", "Ochaco Uraraka", "Shoto Todoroki", "All Might"]},
    {"mal_id": 19, "title": "Monster", "score": 8.87, "rank": 16, "year": 2004, "characters": ["Kenzo Tenma", "Johan Liebert", "Nina Fortner", "Heinrich Lunge", "Anna Liebert"]},
    {"mal_id": 32281, "title": "Kimi no Na wa", "score": 8.84, "rank": 17, "year": 2016, "characters": ["Mitsuha Miyamizu", "Taki Tachibana", "Miki Okudera", "Tessie", "Sayaka"]},
    {"mal_id": 28851, "title": "Koe no Katachi", "score": 8.94, "rank": 18, "year": 2016, "characters": ["Shouya Ishida", "Shouko Nishimiya", "Yuzuru Nishimiya", "Tomohiro Nagatsuka", "Miyoko Sahara"]},
    {"mal_id": 44511, "title": "Chainsaw Man", "score": 8.56, "rank": 19, "year": 2022, "characters": ["Denji", "Power", "Aki Hayakawa", "Makima", "Pochita"]},
    {"mal_id": 50265, "title": "Spy x Family", "score": 8.49, "rank": 20, "year": 2022, "characters": ["Loid Forger", "Yor Forger", "Anya Forger", "Bond Forger", "Damian Desmond"]},
    {"mal_id": 9756, "title": "Mahou Shoujo Madoka Magica", "score": 8.35, "rank": 21, "year": 2011, "characters": ["Madoka Kaname", "Homura Akemi", "Mami Tomoe", "Sayaka Miki", "Kyoko Sakura"]},
    {"mal_id": 199, "title": "Sen to Chihiro no Kamikakushi", "score": 8.78, "rank": 22, "year": 2001, "characters": ["Chihiro Ogino", "Haku", "Yubaba", "Zeniba", "No-Face"]},
    {"mal_id": 47194, "title": "Bocchi the Rock!", "score": 8.77, "rank": 23, "year": 2022, "characters": ["Hitori Gotou", "Nijika Ijichi", "Ryo Yamada", "Ikuyo Kita", "Seika Ijichi"]},
    {"mal_id": 52701, "title": "Oshi no Ko", "score": 8.41, "rank": 24, "year": 2023, "characters": ["Aquamarine Hoshino", "Ruby Hoshino", "Ai Hoshino", "Kana Arima", "Akane Kurokawa"]},
    {"mal_id": 42310, "title": "Cyberpunk: Edgerunners", "score": 8.61, "rank": 25, "year": 2022, "characters": ["David Martinez", "Lucy", "Rebecca", "Maine", "Dorio"]},
    {"mal_id": 37510, "title": "Mob Psycho 100 II", "score": 8.77, "rank": 26, "year": 2019, "characters": ["Shigeo Kageyama", "Arataka Reigen", "Ritsu Kageyama", "Teruki Hanazawa", "Dimple"]},
    {"mal_id": 33352, "title": "Violet Evergarden", "score": 8.65, "rank": 27, "year": 2018, "characters": ["Violet Evergarden", "Gilbert Bougainvillea", "Claudia Hodgins", "Cattleya Baudelaire", "Erica Brown"]},
    {"mal_id": 39486, "title": "Vinland Saga", "score": 8.74, "rank": 28, "year": 2019, "characters": ["Thorfinn", "Askeladd", "Canute", "Thors", "Bjorn"]},
    {"mal_id": 820, "title": "Ginga Eiyuu Densetsu", "score": 8.97, "rank": 29, "year": 1988, "characters": ["Reinhard von Lohengramm", "Yang Wen-li", "Siegfried Kircheis", "Paul von Oberstein", "Julian Mintz"]},
    {"mal_id": 431, "title": "Howl no Ugoku Shiro", "score": 8.66, "rank": 30, "year": 2004, "characters": ["Howl", "Sophie Hatter", "Calcifer", "Markl", "Witch of the Waste"]},
    
    # Continue with 31-150...
    {"mal_id": 2904, "title": "Code Geass: Hangyaku no Lelouch R2", "score": 8.91, "rank": 31, "year": 2008, "characters": ["Lelouch Lamperouge", "Suzaku Kururugi", "C.C.", "Kallen Stadtfeld", "Euphemia li Britannia"]},
    {"mal_id": 48316, "title": "Mob Psycho 100 III", "score": 8.81, "rank": 32, "year": 2022, "characters": ["Shigeo Kageyama", "Arataka Reigen", "Ritsu Kageyama", "Teruki Hanazawa", "Dimple"]},
    {"mal_id": 41467, "title": "Bleach: Sennen Kessen-hen", "score": 8.77, "rank": 33, "year": 2022, "characters": ["Ichigo Kurosaki", "Rukia Kuchiki", "Renji Abarai", "Byakuya Kuchiki", "Yhwach"]},
    {"mal_id": 36838, "title": "Seishun Buta Yarou", "score": 8.22, "rank": 34, "year": 2018, "characters": ["Sakuta Azusagawa", "Mai Sakurajima", "Rio Futaba", "Tomoe Koga", "Kaede Azusagawa"]},
    {"mal_id": 35180, "title": "3-gatsu no Lion 2nd Season", "score": 8.76, "rank": 35, "year": 2017, "characters": ["Rei Kiriyama", "Akari Kawamoto", "Hinata Kawamoto", "Momo Kawamoto", "Kyouko Kouda"]},
    {"mal_id": 33, "title": "Kenpuu Denki Berserk", "score": 8.54, "rank": 36, "year": 1997, "characters": ["Guts", "Griffith", "Casca", "Judeau", "Pippin"]},
    {"mal_id": 40456, "title": "Kaguya-sama: First Kiss", "score": 8.81, "rank": 37, "year": 2022, "characters": ["Miyuki Shirogane", "Kaguya Shinomiya", "Chika Fujiwara", "Yu Ishigami", "Miko Iino"]},
    {"mal_id": 42963, "title": "Odd Taxi", "score": 8.70, "rank": 38, "year": 2021, "characters": ["Hiroshi Odokawa", "Shirakawa", "Kabasawa", "Dobu", "Taeko"]},
    {"mal_id": 22319, "title": "Tokyo Ghoul", "score": 7.78, "rank": 39, "year": 2014, "characters": ["Ken Kaneki", "Touka Kirishima", "Hideyoshi Nagachika", "Uta", "Nishiki Nishio"]},
    {"mal_id": 32935, "title": "Haikyuu!!: Karasuno Koukou vs Shiratorizawa", "score": 8.77, "rank": 40, "year": 2016, "characters": ["Shouyou Hinata", "Tobio Kageyama", "Kei Tsukishima", "Yu Nishinoya", "Ryuunosuke Tanaka"]},
    
    {"mal_id": 34572, "title": "Black Clover", "score": 8.15, "rank": 41, "year": 2017, "characters": ["Asta", "Yuno", "Noelle Silva", "Yami Sukehiro", "Luck Voltia"]},
    {"mal_id": 35839, "title": "Darling in the FranXX", "score": 7.18, "rank": 42, "year": 2018, "characters": ["Hiro", "Zero Two", "Ichigo", "Goro", "Miku"]},
    {"mal_id": 23273, "title": "Shigatsu wa Kimi no Uso", "score": 8.64, "rank": 43, "year": 2014, "characters": ["Kousei Arima", "Kaori Miyazono", "Tsubaki Sawabe", "Ryota Watari", "Emi Igawa"]},
    {"mal_id": 34599, "title": "Made in Abyss", "score": 8.68, "rank": 44, "year": 2017, "characters": ["Riko", "Reg", "Nanachi", "Marulk", "Ozen"]},
    {"mal_id": 37349, "title": "Fate/Zero 2nd Season", "score": 8.54, "rank": 45, "year": 2012, "characters": ["Kiritsugu Emiya", "Saber", "Kirei Kotomine", "Gilgamesh", "Rider"]},
    {"mal_id": 37991, "title": "JoJo's Bizarre Adventure: Golden Wind", "score": 8.59, "rank": 46, "year": 2018, "characters": ["Giorno Giovanna", "Bruno Bucciarati", "Guido Mista", "Narancia Ghirga", "Leone Abbacchio"]},
    {"mal_id": 17074, "title": "Monogatari Series: Second Season", "score": 8.76, "rank": 47, "year": 2013, "characters": ["Koyomi Araragi", "Hitagi Senjougahara", "Shinobu Oshino", "Tsubasa Hanekawa", "Mayoi Hachikuji"]},
    {"mal_id": 33095, "title": "Shouwa Genroku Rakugo Shinjuu", "score": 8.55, "rank": 48, "year": 2016, "characters": ["Yotarou", "Yakumo Yurakutei", "Konatsu", "Miyokichi", "Sukeroku"]},
    {"mal_id": 14227, "title": "Tonari no Kaibutsu-kun", "score": 7.46, "rank": 49, "year": 2012, "characters": ["Shizuku Mizutani", "Haru Yoshida", "Asako Natsume", "Souhei Sasahara", "Yuzan Yoshida"]},
    {"mal_id": 24833, "title": "Ansatsu Kyoushitsu", "score": 8.08, "rank": 50, "year": 2015, "characters": ["Koro-sensei", "Nagisa Shiota", "Karma Akabane", "Kaede Kayano", "Irina Jelavic"]},
    
    # Continuing to 150 with popular titles
    {"mal_id": 33050, "title": "Fate/stay night: Heaven's Feel I", "score": 8.19, "rank": 51, "year": 2017, "characters": ["Shirou Emiya", "Sakura Matou", "Rin Tohsaka", "Saber", "Illyasviel von Einzbern"]},
    {"mal_id": 2001, "title": "Tengen Toppa Gurren Lagann", "score": 8.63, "rank": 52, "year": 2007, "characters": ["Simon", "Kamina", "Yoko Littner", "Nia Teppelin", "Viral"]},
    {"mal_id": 21939, "title": "Mushishi Zoku Shou", "score": 8.69, "rank": 53, "year": 2014, "characters": ["Ginko", "Tanyuu Karibusa", "Nui", "Isaza", "Kourou"]},
    {"mal_id": 35180, "title": "3-gatsu no Lion", "score": 8.37, "rank": 54, "year": 2016, "characters": ["Rei Kiriyama", "Akari Kawamoto", "Hinata Kawamoto", "Momo Kawamoto", "Kyouko Kouda"]},
    {"mal_id": 31240, "title": "Re:Zero kara Hajimeru Isekai Seikatsu", "score": 8.23, "rank": 55, "year": 2016, "characters": ["Subaru Natsuki", "Emilia", "Rem", "Ram", "Beatrice"]},
   
    # Add more popular anime continuing through rank 150
    {"mal_id": 37779, "title": "Yakusoku no Neverland", "score": 8.49, "rank": 56, "year": 2019, "characters": ["Emma", "Norman", "Ray", "Isabella", "Don"]},
    {"mal_id": 39617, "title": "Vinland Saga Season 2", "score": 8.79, "rank": 57, "year": 2023, "characters": ["Thorfinn", "Einar", "Canute", "Thorgil", "Ketil"]},
    {"mal_id": 41084, "title": "Made in Abyss: Retsujitsu no Ougonkyou", "score": 8.68, "rank": 58, "year": 2022, "characters": ["Riko", "Reg", "Nanachi", "Faputa", "Vueko"]},
    {"mal_id": 17265, "title": "Log Horizon", "score": 7.61, "rank": 59, "year": 2013, "characters": ["Shiroe", "Akatsuki", "Naotsugu", "Minori", "Touya"]},
    {"mal_id": 39534, "title": "Mushoku Tensei", "score": 8.36, "rank": 60, "year": 2021, "characters": ["Rudeus Greyrat", "Roxy Migurdia", "Sylphiette", "Eris Boreas Greyrat", "Ruijerd Superdia"]},
    
    {"mal_id": 43608, "title": "Kaguya-sama: Ultra Romantic", "score": 9.00, "rank": 61, "year": 2022, "characters": ["Miyuki Shirogane", "Kaguya Shinomiya", "Chika Fujiwara", "Yu Ishigami", "Miko Iino"]},
    {"mal_id": 48926, "title": "Kaguya-sama Season 3", "score": 8.94, "rank": 62, "year": 2022, "characters": ["Miyuki Shirogane", "Kaguya Shinomiya", "Chika Fujiwara", "Yu Ishigami", "Miko Iino"]},
    {"mal_id": 11757, "title": "Sword Art Online", "score": 7.20, "rank": 63, "year": 2012, "characters": ["Kirito", "Asuna", "Klein", "Silica", "Lisbeth"]},
    {"mal_id": 42897, "title": "Gintama: The Final", "score": 8.99, "rank": 64, "year": 2021, "characters": ["Gintoki Sakata", "Kagura", "Shinpachi Shimura", "Hijikata Toushirou", "Takasugi Shinsuke"]},
    {"mal_id": 36896, "title": "Yakusoku no Neverland: Season 1", "score": 8.50, "rank": 65, "year": 2019, "characters": ["Emma", "Norman", "Ray", "Isabella", "Don"]},
    
    {"mal_id": 37349, "title": "Fate/Zero", "score": 8.28, "rank": 66, "year": 2011, "characters": ["Kiritsugu Emiya", "Saber", "Kirei Kotomine", "Gilgamesh", "Rider"]},
    {"mal_id": 431, "title": "Mononoke Hime", "score": 8.70, "rank": 67, "year": 1997, "characters": ["Ashitaka", "San", "Lady Eboshi", "Moro", "Jigo"]},
    {"mal_id": 34561, "title": "Overlord III", "score": 7.92, "rank": 68, "year": 2018, "characters": ["Ainz Ooal Gown", "Albedo", "Shalltear Bloodfallen", "Demiurge", "Cocytus"]},
    {"mal_id": 51179, "title": "Bleach: Thousand-Year Blood War", "score": 8.81, "rank": 69, "year": 2022, "characters": ["Ichigo Kurosaki", "Rukia Kuchiki", "Renji Abarai", "Byakuya Kuchiki", "Yhwach"]},
    {"mal_id": 38101, "title": "Seishun Buta Yarou Movie", "score": 8.59, "rank": 70, "year": 2019, "characters": ["Sakuta Azusagawa", "Mai Sakurajima", "Shouko Makinohara", "Rio Futaba", "Kaede Azusagawa"]},
    
    # Continue with more popular anime through 150
    {"mal_id": 37450, "title": "KonoSuba Movie", "score": 8.42, "rank": 71, "year": 2019, "characters": ["Kazuma Satou", "Aqua", "Megumin", "Darkness", "Yunyun"]},
    {"mal_id": 50709, "title": "Bocchi the Rock!", "score": 8.85, "rank": 72, "year": 2022, "characters": ["Hitori Gotou", "Nijika Ijichi", "Ryo Yamada", "Ikuyo Kita", "Seika Ijichi"]},
    {"mal_id": 37987, "title": "Violet Evergarden Movie", "score": 8.68, "rank": 73, "year": 2020, "characters": ["Violet Evergarden", "Gilbert Bougainvillea", "Claudia Hodgins", "Cattleya Baudelaire", "Dietfried Bougainvillea"]},
    {"mal_id": 2236, "title": "Toki wo Kakeru Shoujo", "score": 8.11, "rank": 74, "year": 2006, "characters": ["Makoto Konno", "Chiaki Mamiya", "Kousuke Tsuda", "Yuri Hayakawa", "Kazuko Yoshiyama"]},
    {"mal_id": 40591, "title": "Kaguya-sama Season 2", "score": 8.64, "rank": 75, "year": 2020, "characters": ["Miyuki Shirogane", "Kaguya Shinomiya", "Chika Fujiwara", "Yu Ishigami", "Miko Iino"]},
    
    {"mal_id": 22147, "title": "Amagi Brilliant Park", "score": 7.45, "rank": 76, "year": 2014, "characters": ["Seiya Kanie", "Isuzu Sento", "Latifa Fleuranza", "Moffle", "Macaron"]},
    {"mal_id": 30831, "title": "Kono Subarashii Sekai ni Shukufuku wo!", "score": 8.10, "rank": 77, "year": 2016, "characters": ["Kazuma Satou", "Aqua", "Megumin", "Darkness", "Wiz"]},
    {"mal_id": 37989, "title": "Golden Kamuy Season 2", "score": 8.33, "rank": 78, "year": 2018, "characters": ["Saichi Sugimoto", "Asirpa", "Hyakunosuke Ogata", "Yoshitake Shiraishi", "Toshizou Hijikata"]},
    {"mal_id": 48895, "title": "Sono Bisque Doll wa Koi wo Suru", "score": 8.17, "rank": 79, "year": 2022, "characters": ["Wakana Gojo", "Marin Kitagawa", "Sajuna Inui", "Shinju Inui", "Nowa Sugaya"]},
    {"mal_id": 40540, "title": "Mushoku Tensei II", "score": 8.64, "rank": 80, "year": 2023, "characters": ["Rudeus Greyrat", "Roxy Migurdia", "Sylphiette", "Eris Boreas Greyrat", "Cliff Grimoire"]},
    
    {"mal_id": 34280, "title": "Shokugeki no Souma: San no Sara", "score": 8.04, "rank": 81, "year": 2017, "characters": ["Souma Yukihira", "Erina Nakiri", "Megumi Tadokoro", "Takumi Aldini", "Isami Aldini"]},
    {"mal_id": 18679, "title": "Kill la Kill", "score": 7.99, "rank": 82, "year": 2013, "characters": ["Ryuuko Matoi", "Satsuki Kiryuuin", "Mako Mankanshoku", "Senketsu", "Aikurou Mikisugi"]},
    {"mal_id": 20583, "title": "Noragami", "score": 7.94, "rank": 83, "year": 2014, "characters": ["Yato", "Hiyori Iki", "Yukine", "Kofuku", "Daikoku"]},
    {"mal_id": 6702, "title": "Fairy Tail", "score": 7.57, "rank": 84, "year": 2009, "characters": ["Natsu Dragneel", "Lucy Heartfilia", "Gray Fullbuster", "Erza Scarlet", "Happy"]},
    {"mal_id": 23755, "title": "Nanatsu no Taizai", "score": 7.63, "rank": 85, "year": 2014, "characters": ["Meliodas", "Elizabeth Liones", "Hawk", "Diane", "Ban"]},
    
    {"mal_id": 34566, "title": "Ballroom e Youkoso", "score": 8.19, "rank": 86, "year": 2017, "characters": ["Tatara Fujita", "Chinatsu Hiyama", "Shizuku Hanaoka", "Kaname Sengoku", "Mako Akagi"]},
    {"mal_id": 33255, "title": "Saiki Kusuo no Psi-nan", "score": 8.41, "rank": 87, "year": 2016, "characters": ["Kusuo Saiki", "Shun Kaidou", "Riki Nendou", "Kokomi Teruhashi", "Aren Kuboyasu"]},
    {"mal_id": 37956, "title": "Dororo", "score": 8.23, "rank": 88, "year": 2019, "characters": ["Hyakkimaru", "Dororo", "Jukai", "Daigo Kagemitsu", "Tahomaru"]},
    {"mal_id": 52198, "title": "BLUE LOCK", "score": 8.23, "rank": 89, "year": 2022, "characters": ["Yoichi Isagi", "Meguru Bachira", "Rensuke Kunigami", "Hyoma Chigiri", "Gin Gagamaru"]},
    {"mal_id": 36475, "title": "Sword Art Online: Alicization", "score": 7.55, "rank": 90, "year": 2018, "characters": ["Kirito", "Eugeo", "Alice Zuberg", "Asuna", "Cardinal"]},
    
    {"mal_id": 22535, "title": "Kiseijuu: Sei no Kakuritsu", "score": 8.33, "rank": 91, "year": 2014, "characters": ["Shinichi Izumi", "Migi", "Satomi Murano", "Reiko Tamura", "Ryouko Tamiya"]},
    {"mal_id": 37521, "title": "Vinland Saga", "score": 8.74, "rank": 92, "year": 2019, "characters": ["Thorfinn", "Askeladd", "Canute", "Thors", "Bjorn"]},
    {"mal_id": 43299, "title": "Ore dake Haireru Kakushi Dungeon", "score": 6.32, "rank": 93, "year": 2021, "characters": ["Noir Stalgia", "Emma Brightness", "Olivia Servant", "Lola Meroune", "Alice"]},
    {"mal_id": 40099, "title": "Kingdom Season 3", "score": 8.55, "rank": 94, "year": 2020, "characters": ["Xin", "Ying Zheng", "He Liao Diao", "Qiang Lei", "Bi Hei"]},
    {"mal_id": 34618, "title": "Mahoutsukai no Yome", "score": 8.07, "rank": 95, "year": 2017, "characters": ["Chise Hatori", "Elias Ainsworth", "Ruth", "Silky", "Angelica Barley"]},
    
    {"mal_id": 35839, "title": "Darling in the Franxx", "score": 7.20, "rank": 96, "year": 2018, "characters": ["Hiro", "Zero Two", "Ichigo", "Goro", "Miku"]},
    {"mal_id": 37105, "title": "Grand Blue", "score": 8.44, "rank": 97, "year": 2018, "characters": ["Iori Kitahara", "Kouhei Imamura", "Chisa Kotegawa", "Nanaka Kotegawa", "Shinji Tokita"]},
    {"mal_id": 40357, "title": "Horimiya", "score": 8.21, "rank": 98, "year": 2021, "characters": ["Kyouko Hori", "Izumi Miyamura", "Tooru Ishikawa", "Yuki Yoshikawa", "Remi Ayasaki"]},
    {"mal_id": 48561, "title": "Jujutsu Kaisen 0", "score": 8.42, "rank": 99, "year": 2021, "characters": ["Yuta Okkotsu", "Rika Orimoto", "Satoru Gojo", "Maki Zenin", "Toge Inumaki"]},
    {"mal_id": 51009, "title": "Jujutsu Kaisen 2nd Season", "score": 8.75, "rank": 100, "year": 2023, "characters": ["Yuji Itadori", "Megumi Fushiguro", "Nobara Kugisaki", "Satoru Gojo", "Suguru Geto"]},
    
    # Final 50 to reach 150
    {"mal_id": 489, "title": "Mononoke", "score": 8.41, "rank": 101, "year": 2007, "characters": ["Kusuriuri", "Kayo", "Ochuu", "Lady Ruri", "Sasaki"]},
    {"mal_id": 34798, "title": "Hinamatsuri", "score": 8.25, "rank": 102, "year": 2018, "characters": ["Hina", "Nitta Yoshifumi", "Anzu", "Hitomi Mishima", "Hitoshi Mishima"]},
    {"mal_id": 2167, "title": "Clannad: After Story", "score": 8.93, "rank": 103, "year": 2008, "characters": ["Tomoya Okazaki", "Nagisa Furukawa", "Ushio Okazaki", "Kyou Fujibayashi", "Tomoyo Sakagami"]},
    {"mal_id": 52196, "title": "Spy x Family Part 2", "score": 8.25, "rank": 104, "year": 2022, "characters": ["Loid Forger", "Yor Forger", "Anya Forger", "Bond Forger", "Fiona Frost"]},
    {"mal_id": 33486, "title": "Kobayashi-san Chi no Maid Dragon", "score": 7.93, "rank": 105, "year": 2017, "characters": ["Tooru", "Kobayashi", "Kanna Kamui", "Elma", "Lucoa"]},
    
    {"mal_id": 32937, "title": "Karakai Jouzu no Takagi-san", "score": 7.73, "rank": 106, "year": 2018, "characters": ["Takagi", "Nishikata", "Mina", "Yukari", "Sanae"]},
    {"mal_id": 34591, "title": "Natsume Yuujinchou Roku", "score": 8.60, "rank": 107, "year": 2017, "characters": ["Natsume Takashi", "Nyanko-sensei", "Taki Tooru", "Tanuma Kaname", "Natori Shuuichi"]},
    {"mal_id": 31988, "title": "Sakamoto desu ga?", "score": 7.54, "rank": 108, "year": 2016, "characters": ["Sakamoto", "Atsushi Maeda", "Kubota Yoshinobu", "Sera", "Acchan"]},
    {"mal_id": 9617, "title": "K-On!!",  "score": 8.17, "rank": 109, "year": 2010, "characters": ["Yui Hirasawa", "Mio Akiyama", "Ritsu Tainaka", "Tsumugi Kotobuki", "Azusa Nakano"]},
    {"mal_id": 37450, "title": "Re:Zero Season 2", "score": 8.27, "rank": 110, "year": 2020, "characters": ["Subaru Natsuki", "Emilia", "Rem", "Ram", "Beatrice"]},
    
    {"mal_id": 33352, "title": "Violet Evergarden Series", "score": 8.67, "rank": 111, "year": 2018, "characters": ["Violet Evergarden", "Gilbert Bougainvillea", "Claudia Hodgins", "Cattleya Baudelaire", "Erica Brown"]},
    {"mal_id": 36098, "title": "Kimi no Suizou wo Tabetai", "score": 8.54, "rank": 112, "year": 2018, "characters": ["Haruki Shiga", "Sakura Yamauchi", "Kyouko", "Takahiro", "Gum-kun"]},
    {"mal_id": 37999, "title": "Demon Slayer Movie", "score": 8.40, "rank": 113, "year": 2020, "characters": ["Tanjiro Kamado", "Nezuko Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Kyojuro Rengoku"]},
    {"mal_id": 48926, "title": "Dr. Stone: New World", "score": 8.16, "rank": 114, "year": 2023, "characters": ["Senku Ishigami", "Taiju Oki", "Yuzuriha Ogawa", "Chrome", "Kohaku"]},
    {"mal_id": 35247, "title": "Owarimonogatari 2", "score": 8.87, "rank": 115, "year": 2017, "characters": ["Koyomi Araragi", "Hitagi Senjougahara", "Shinobu Oshino", "Tsubasa Hanekawa", "Mayoi Hachikuji"]},
    
    {"mal_id": 38040, "title": "Yagate Kimi ni Naru", "score": 7.89, "rank": 116, "year": 2018, "characters": ["Yuu Koito", "Touko Nanami", "Sayaka Saeki", "Riko Hakozaki", "Akari Hyuuga"]},
    {"mal_id": 36475, "title": "Sword Art Online Alicization", "score": 7.57, "rank": 117, "year": 2018, "characters": ["Kirito", "Eugeo", "Alice Zuberg", "Asuna", "Cardinal"]},
    {"mal_id": 15335, "title": "Gintama Movie: Final", "score": 8.76, "rank": 118, "year": 2013, "characters": ["Gintoki Sakata", "Kagura", "Shinpachi Shimura", "Hijikata Toushirou", "Okita Sougo"]},
    {"mal_id": 38481, "title": "Kaguya-sama Season 1", "score": 8.40, "rank": 119, "year": 2019, "characters": ["Miyuki Shirogane", "Kaguya Shinomiya", "Chika Fujiwara", "Yu Ishigami", "Ai Hayasaka"]},
    {"mal_id": 41488, "title": "Fruits Basket 2nd Season", "score": 8.74, "rank": 120, "year": 2020, "characters": ["Tohru Honda", "Kyo Souma", "Yuki Souma", "Shigure Souma", "Kagura Souma"]},
    
    {"mal_id": 37976, "title": "Yakusoku no Neverland Season 1", "score": 8.49, "rank": 121, "year": 2019, "characters": ["Emma", "Norman", "Ray", "Isabella", "Don"]},
    {"mal_id": 48548, "title": "Dungeon ni Deai wo Motomeru", "score": 7.24, "rank": 122, "year": 2015, "characters": ["Bell Cranel", "Hestia", "Ais Wallenstein", "Liliruca Arde", "Welf Crozzo"]},
    {"mal_id": 49926, "title": "Bocchi the Rock!", "score": 8.91, "rank": 123, "year": 2022, "characters": ["Hitori Gotou", "Nijika Ijichi", "Ryo Yamada", "Ikuyo Kita", "Seika Ijichi"]},
    {"mal_id": 43969, "title": "Tate no Yuusha no Nariagari Season 2", "score": 6.86, "rank": 124, "year": 2022, "characters": ["Naofumi Iwatani", "Raphtalia", "Filo", "Melty Melromark", "Rishia Ivyred"]},
    {"mal_id": 34599, "title": "Made in Abyss Season 1", "score": 8.68, "rank": 125, "year": 2017, "characters": ["Riko", "Reg", "Nanachi", "Marulk", "Ozen"]},
    
    {"mal_id": 40059, "title": "Golden Kamuy Season 3", "score": 8.45, "rank": 126, "year": 2020, "characters": ["Saichi Sugimoto", "Asirpa", "Hyakunosuke Ogata", "Yoshitake Shiraishi", "Toshizou Hijikata"]},
    {"mal_id": 35711, "title": "Yuru Camp", "score": 7.68, "rank": 127, "year": 2018, "characters": ["Rin Shima", "Nadeshiko Kagamihara", "Chiaki Oogaki", "Aoi Inuyama", "Ena Saitou"]},
    {"mal_id": 42938, "title": "Fruits Basket: The Final", "score": 9.02, "rank": 128, "year": 2021, "characters": ["Tohru Honda", "Kyo Souma", "Yuki Souma", "Shigure Souma", "Akito Souma"]},
    {"mal_id": 37393, "title": "Demon Slayer", "score": 8.51, "rank": 129, "year": 2019, "characters": ["Tanjiro Kamado", "Nezuko Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Giyu Tomioka"]},
    {"mal_id": 48453, "title": "Kimetsu no Yaiba: Katanakaji no Sato-hen", "score": 8.31, "rank": 130, "year": 2023, "characters": ["Tanjiro Kamado", "Nezuko Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Mitsuri Kanroji"]},
    
    {"mal_id": 49387, "title": "Vinland Saga Season 2", "score": 8.79, "rank": 131, "year": 2023, "characters": ["Thorfinn", "Einar", "Canute", "Thorgil", "Ketil"]},
    {"mal_id": 50172, "title": "Mob Psycho 100 III", "score": 8.84, "rank": 132, "year": 2022, "characters": ["Shigeo Kageyama", "Arataka Reigen", "Ritsu Kageyama", "Teruki Hanazawa", "Dimple"]},
    {"mal_id": 37450, "title": "Kono Subarashii Sekai ni Shukufuku wo! Movie", "score": 8.42, "rank": 133, "year": 2019, "characters": ["Kazuma Satou", "Aqua", "Megumin", "Darkness", "Yunyun"]},
    {"mal_id": 50590, "title": "Chainsaw Man", "score": 8.56, "rank": 134, "year": 2022, "characters": ["Denji", "Power", "Aki Hayakawa", "Makima", "Pochita"]},
    {"mal_id": 50380, "title": "Lycoris Recoil", "score": 8.01, "rank": 135, "year": 2022, "characters": ["Chisato Nishikigi", "Takina Inoue", "Mizuki Nakahara", "Kurumi", "Mika"]},
    
    {"mal_id": 52034, "title": "Oshi no Ko", "score": 8.41, "rank": 136, "year": 2023, "characters": ["Aquamarine Hoshino", "Ruby Hoshino", "Ai Hoshino", "Kana Arima", "Akane Kurokawa"]},
    {"mal_id": 48413, "title": "Komi-san wa, Comyushou desu. 2nd Season", "score": 7.93, "rank": 137, "year": 2022, "characters": ["Shouko Komi", "Hitohito Tadano", "Najimi Osana", "Himiko Agari", "Omoharu Nakanaka"]},
    {"mal_id": 52741, "title": "Tengoku Daimakyou", "score": 8.05, "rank": 138, "year": 2023, "characters": ["Maru", "Kiruko", "Tokio", "Kona", "Mimihime"]},
    {"mal_id": 43969, "title": "The Rising of the Shield Hero Season 2", "score": 6.86, "rank": 139, "year": 2022, "characters": ["Naofumi Iwatani", "Raphtalia", "Filo", "Melty Melromark", "Ost Hourai"]},
    {"mal_id": 51535, "title": "Shingeki no Kyojin: The Final Season Part 3", "score": 8.91, "rank": 140, "year": 2023, "characters": ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman", "Reiner Braun"]},
    
    {"mal_id": 33050, "title": "Fate/stay night: Heaven's Feel I", "score": 8.19, "rank": 141, "year": 2017, "characters": ["Shirou Emiya", "Sakura Matou", "Rin Tohsaka", "Saber", "Illyasviel von Einzbern"]},
    {"mal_id": 53049, "title": "Boku no Hero Academia Season 7", "score": 7.96, "rank": 142, "year": 2024, "characters": ["Izuku Midoriya", "Katsuki Bakugo", "Ochaco Uraraka", "Shoto Todoroki", "All Might"]},
    {"mal_id": 52588, "title": "Pluto", "score": 8.61, "rank": 143, "year": 2023, "characters": ["Gesicht", "Atom", "Epsilon", "Brau 1589", "Uran"]},
    {"mal_id": 48413, "title": "Komi Can't Communicate Season 2", "score": 7.93, "rank": 144, "year": 2022, "characters": ["Shouko Komi", "Hitohito Tadano", "Najimi Osana", "Himiko Agari", "Ren Yamai"]},
    {"mal_id": 49979, "title": "Shoujo☆Kageki Revue Starlight Movie", "score": 8.02, "rank": 145, "year": 2021, "characters": ["Hikari Kagura", "Karen Aijou", "Junna Hoshimi", "Nana Daiba", "Mahiru Tsuyuzaki"]},
    
    {"mal_id": 50709, "title": "Bocchi the Rock!", "score": 8.77, "rank": 146, "year": 2022, "characters": ["Hitori Gotou", "Nijika Ijichi", "Ryo Yamada", "Ikuyo Kita", "Seika Ijichi"]},
    {"mal_id": 39551, "title": "Shadows House", "score": 7.77, "rank": 147, "year": 2021, "characters": ["Emilyko", "Kate Shadow", "Shaun", "Ricky", "Lou"]},
    {"mal_id": 51122, "title": "Trigun Stampede", "score": 8.25, "rank": 148, "year": 2023, "characters": ["Vash the Stampede", "Meryl Stryfe", "Roberto De Niro", "Nicholas D. Wolfwood", "Knives Millions"]},
    {"mal_id": 48549, "title": "Tomo-chan wa Onnanoko!", "score": 7.76, "rank": 149, "year": 2023, "characters": ["Tomo Aizawa", "Junichiro Kubota", "Misuzu Gundou", "Carol Olston", "Kousuke Misaki"]},
    {"mal_id": 48452, "title": "Raven of the Inner Palace", "score": 7.63, "rank": 150, "year": 2022, "characters": ["Shouxue", "Jiujiu", "Ye Ming", "Gao Jun", "Wen Ying"]}
]
