# DC Universe Character Bank - 250 Female Heroes & Villains
# Raw names for Nano Banana cosplay presets
# "You know how to Google your own refs"

DC_CHARACTER_BANK = [
    # Amazons & Wonder Family (1-8)
    "Wonder Woman",
    "Nubia",
    "Hippolyta",
    "Artemis of Bana Mighdall",
    "Donna Troy",
    "Wonder Girl Cassie Sandsmark",
    "Yara Flor",
    "Fury Lyta Trevor",
    
    # Super Family (9-17)
    "Supergirl Kara Zor El",
    "Supergirl Linda Danvers",
    "Power Girl",
    "Lois Lane Superwoman",
    "Lucy Lane Superwoman",
    "Lana Lang Superwoman",
    "Superwoman of the Crime Syndicate",
    "Mera",
    "Zatanna",
    
    # Birds of Prey & Justice League (18-25)
    "Black Canary Dinah Lance",
    "Vixen Mari McCabe",
    "Hawkgirl Shayera Hol",
    "Hawkgirl Kendra Saunders",
    "Starfire",
    "Raven",
    "Bumblebee Karen Beecher",
    "Miss Martian M gann M orzz",
    
    # Bat Family (26-51)
    "Batgirl Barbara Gordon",
    "Batgirl Cassandra Cain",
    "Batgirl Stephanie Brown",
    "Batwoman Kate Kane",
    "Spoiler Stephanie Brown",
    "Orphan Cassandra Cain",
    "Huntress Helena Bertinelli",
    "Huntress Helena Wayne",
    "Bluebird Harper Row",
    "Oracle Barbara Gordon",
    "Catwoman Selina Kyle",
    "Harley Quinn",
    "Poison Ivy",
    "Talia al Ghul",
    "Nyssa al Ghul",
    "Lady Shiva",
    "Lady Vic",
    "Tarantula Catalina Flores",
    "Renee Montoya as The Question",
    "Manhunter Kate Spencer",
    "Lady Blackhawk Zinda Blake",
    "Misfit Charlotte Gage Radcliffe",
    "Red Alice Beth Kane",
    "Flamebird Bette Kane",
    "Gotham Girl Claire Clover",
    "Julia Pennyworth",
    
    # New Gods & JLI Era (52-60)
    "Big Barda",
    "Maxima",
    "Fire Beatriz da Costa",
    "Ice Tora Olafsdotter",
    "Crimson Fox",
    "Gypsy Cindy Reynolds",
    "Doctor Light Kimiyo Hoshi",
    "Stargirl Courtney Whitmore",
    "Cyclone Maxine Hunkel",
    
    # Speedsters & Legacy Heroes (61-70)
    "Liberty Belle Jesse Chambers",
    "Jesse Quick",
    "XS Jenni Ognats",
    "Jade Jennifer Lynn Hayden",
    "Thunder Anissa Pierce",
    "Lightning Jennifer Pierce",
    "Rocket Raquel Ervin",
    "Grace Choi",
    "Katana Tatsu Yamashiro",
    "Emiko Queen Red Arrow",
    
    # Teen Titans & Young Heroes (71-91)
    "Speedy Mia Dearden",
    "Ravager Rose Wilson",
    "Terra Tara Markov",
    "Argent",
    "Pantha",
    "Kole",
    "Empress Anita Fite",
    "Solstice Kiran Singh",
    "Skitter Celine Patterson",
    "Dove Dawn Granger",
    "Hawk Holly Granger",
    "Animal Girl Maxine Baker",
    "Dolphin",
    "Looker Emily Briggs",
    "Phantom Lady",
    "Firehawk Lorraine Reilly",
    "Skyrocket Celia Forrestal",
    "Shining Knight Ystina",
    "Amethyst Princess of Gemworld",
    "Traci Thirteen",
    "Tomorrow Woman",
    
    # Shadowpact & Freedom Fighters (92-101)
    "Nightshade Eve Eden",
    "Lady Quark",
    "Judomaster Sonia Sato",
    "Crimson Avenger Jill Carlyle",
    "Rima the Jungle Girl",
    "Elasti Girl Rita Farr",
    "Negative Woman Valentina Vostok",
    "Crazy Jane",
    "Celsius Arani Desai",
    "Element Woman Emily Sung",
    
    # Green Lanterns & Corps (102-111)
    "Jessica Cruz Green Lantern",
    "Katma Tui",
    "Arisia Rrab",
    "Soranik Natu",
    "Laira",
    "Bleez Red Lantern",
    "Fatality",
    "Star Sapphire Carol Ferris",
    "Star Sapphire Deborah Darnell",
    "Lyssa Drak",
    
    # Supergirl Variants & Legion (112-131)
    "Cir El",
    "Matrix Supergirl",
    "Laurel Gand",
    "Saturn Girl",
    "Phantom Girl",
    "Shadow Lass",
    "Shrinking Violet",
    "Lightning Lass",
    "Dream Girl",
    "Dawnstar",
    "Princess Projectra",
    "Sensor Girl",
    "White Witch",
    "Duo Damsel",
    "Triplicate Girl",
    "Andromeda",
    "Emerald Empress",
    "Night Girl",
    "Kid Quantum Jazmin Cullen",
    "Kinetix Zoe Saugin",
    
    # More Legion & Atlantis (132-140)
    "Monstress",
    "Apparition Tinya Wazzo",
    "Harbinger Lyla Michaels",
    "Firebrand Danette Reilly",
    "Ice Maiden Sigrid Nansen",
    "Siren Hila",
    "Tula Aquagirl",
    "Aquagirl Lorena Marquez",
    "Isis Adrianna Tomaz",
    
    # Villains - Wonder Woman Rogues (141-148)
    "Cheetah Priscilla Rich",
    "Cheetah Deborah Domaine",
    "Cheetah Barbara Ann Minerva",
    "Giganta",
    "Silver Banshee",
    "Livewire",
    "Magpie",
    "Nocturna",
    
    # Villains - Various (149-167)
    "Roulette",
    "Cheshire Jade Nguyen",
    "Queen Bee Zazzala",
    "Granny Goodness",
    "Lashina",
    "Mad Harriet",
    "Knockout",
    "Mercy Graves",
    "Amanda Waller",
    "White Rabbit Jaina Hudson",
    "Jezebel Jet",
    "Scandal Savage",
    "Tigress Paula Brooks",
    "Tigress Artemis Crock",
    "Silver Swan",
    "Doctor Poison",
    "Veronica Cale",
    "Queen Clea",
    "Grail",
    
    # Magical Villains (168-175)
    "Circe",
    "Enchantress June Moone",
    "Tala",
    "Morgaine le Fey",
    "Blackfire Komand r",
    "Blaze",
    "Mongal",
    "Faora",
    
    # More Villains (176-195)
    "Ursa",
    "Killer Frost Caitlin Snow",
    "Killer Frost Crystal Frost",
    "Killer Frost Louise Lincoln",
    "Plastique",
    "Starling Evelyn Crawford",
    "Voodoo Priscilla Kitaen",
    "Zealot",
    "Jenny Sparks",
    "Jenny Quantum",
    "Swift Shen Li Min",
    "Rose and Thorn Rose Canton",
    "Thorn Rhosyn Forrest",
    "White Canary",
    "Black Alice",
    "Jinx",
    "Shimmer",
    "Indigo Brainiac 8",
    "Bombshell",
    "Nightfall",
    
    # Mystics & Others (196-213)
    "Whisper A Daire",
    "Black Orchid",
    "Madame Xanadu",
    "Arella",
    "Omen Lilith Clay",
    "Strix Mary Turner",
    "Talon female Court of Owls assassin",
    "Maggie Sawyer",
    "Linda Park",
    "Iris West second generation speedster version",
    "Maxine Gibson",
    "Inque",
    "Dana Tan",
    "Sasha Bordeaux",
    "Element Girl Urania Blackwell",
    "Luma Lynai",
    "Shay Veritas",
    "Amanda Spence",
    
    # Supporting Cast (214-226)
    "Lois Lane standard",
    "Lana Lang standard",
    "Chloe Sullivan",
    "Nia Nal Dreamer",
    "Alex Danvers",
    "Kara Danvers Supergirl TV",
    "Lena Luthor",
    "Zari Tomaz",
    "Zari Tarazi",
    "Astra In Ze",
    "Alura Zor El",
    "Nyssa Raatko TV",
    "Vixen Mari McCabe TV",
    
    # TV Versions (227-236)
    "Vixen Amaya Jiwe TV",
    "Thunder Anissa Pierce TV",
    "Lightning Jennifer Pierce TV",
    "Grace Choi TV",
    "Tula Aquagirl animated",
    "Arrowette Cissie King Jones",
    "Secret Greta Hayes",
    "Wonder Girl Young Justice Cassie",
    "Batgirl Young Justice Barbara",
    "Spoiler Young Justice Stephanie",
    
    # Marvel Family & Animated (237-250)
    "Mary Marvel",
    "Black Mary corrupted Mary Marvel",
    "Lois Lane animated",
    "Supergirl DCAU",
    "Shayera Hol animated",
    "Vixen DCAU",
    "Huntress DCAU",
    "Fire DCAU",
    "Ice DCAU",
    "Dr Light animated",
    "Giganta animated",
    "Cheetah animated",
    "Livewire animated",
    "Superwoman animated Crime Syndicate"
]

# Total: 250 characters
print(f"DC Character Bank loaded: {len(DC_CHARACTER_BANK)} characters")

# Categories for quick access
AMAZONS = DC_CHARACTER_BANK[0:8]
SUPER_FAMILY = DC_CHARACTER_BANK[8:17]
BAT_FAMILY = DC_CHARACTER_BANK[25:51]
GREEN_LANTERNS = DC_CHARACTER_BANK[101:111]
LEGION = DC_CHARACTER_BANK[113:131]
VILLAINS = DC_CHARACTER_BANK[140:195]
TV_VERSIONS = DC_CHARACTER_BANK[226:250]
