# Male Character Bank - 100 Male Characters
# Matching genres: DC, Anime, Movie Icons
# For Yuki Brain & Nanobanana

MALE_CHARACTER_BANK = [
    # --- DC UNIVERSE (33) ---
    "Batman Bruce Wayne",
    "Superman Clark Kent",
    "The Joker",
    "Nightwing Dick Grayson",
    "Red Hood Jason Todd",
    "The Flash Barry Allen",
    "Green Lantern Hal Jordan",
    "Aquaman Arthur Curry",
    "Cyborg Victor Stone",
    "Shazam Billy Batson",
    "Black Adam",
    "Green Arrow Oliver Queen",
    "Deathstroke Slade Wilson",
    "Lex Luthor",
    "General Zod",
    "Darkseid",
    "Brainiac",
    "Bane",
    "The Riddler",
    "Two-Face Harvey Dent",
    "Scarecrow Jonathan Crane",
    "The Penguin Oswald Cobblepot",
    "Sinestro",
    "Atrocitus",
    "Hawkman Carter Hall",
    "Doctor Fate",
    "John Constantine",
    "Beast Boy",
    "Robin Damian Wayne",
    "Blue Beetle Jaime Reyes",
    "Booster Gold",
    "Reverse Flash Eobard Thawne",
    "Captain Cold",

    # --- ANIME ICONS (33) ---
    "Goku (Dragon Ball)",
    "Vegeta (Dragon Ball)",
    "Naruto Uzumaki",
    "Sasuke Uchiha",
    "Kakashi Hatake",
    "Monkey D. Luffy",
    "Roronoa Zoro",
    "Sanji Vinsmoke",
    "Ichigo Kurosaki",
    "Sosuke Aizen",
    "Edward Elric",
    "Roy Mustang",
    "Levi Ackerman",
    "Eren Yeager",
    "Tanjiro Kamado",
    "Gojo Satoru",
    "Yuji Itadori",
    "Ryomen Sukuna",
    "Izuku Midoriya (Deku)",
    "Katsuki Bakugo",
    "All Might",
    "Saitama (One Punch Man)",
    "Genos",
    "Spike Spiegel",
    "Light Yagami",
    "L Lawliet",
    "Lelouch Lamperouge",
    "Guts (Berserk)",
    "Griffith (Berserk)",
    "Kenshin Himura",
    "Gon Freecss",
    "Killua Zoldyck",
    "Sattru Gojo",

    # --- MOVIE ICONS (34) ---
    "Indiana Jones",
    "Han Solo",
    "Luke Skywalker",
    "Darth Vader",
    "Kylo Ren",
    "Aragorn",
    "Legolas Greenleaf",
    "Gandalf",
    "Neo (The Matrix)",
    "Morpheus",
    "Agent Smith",
    "Jack Sparrow",
    "James Bond 007",
    "Ethan Hunt",
    "John Wick",
    "The Terminator T-800",
    "Rocky Balboa",
    "John Rambo",
    "Maverick (Top Gun)",
    "Tony Stark Iron Man",
    "Steve Rogers Captain America",
    "Thor Odinson",
    "Bruce Banner Hulk",
    "T'Challa Black Panther",
    "Wolverine Logan",
    "Magneto Erik Lehnsherr",
    "Professor X Charles Xavier",
    "Deadpool Wade Wilson",
    "Maximus Decimus Meridius",
    "Tyler Durden",
    "Forrest Gump",
    "Mad Max Rockatansky",
    "Rick Deckard",
    "K (Blade Runner 2049)"
]

print(f"Male Character Bank loaded: {len(MALE_CHARACTER_BANK)} characters")
