# Movie Stars Character Bank - 250 Female Actresses
# Raw names for cosplay engine casting references
# "Quarter thousand faces - snacks for days"

MOVIE_STARS_BANK = [
    # Oscar Winners & A-List (1-25)
    "Viola Davis",
    "Meryl Streep",
    "Scarlett Johansson",
    "Angela Bassett",
    "Lupita Nyong'o",
    "Regina King",
    "Cate Blanchett",
    "Natalie Portman",
    "Charlize Theron",
    "Nicole Kidman",
    "Julia Roberts",
    "Sandra Bullock",
    "Halle Berry",
    "Taraji P Henson",
    "Octavia Spencer",
    "Jennifer Lawrence",
    "Anne Hathaway",
    "Amy Adams",
    "Emma Stone",
    "Florence Pugh",
    "Zendaya",
    "Saoirse Ronan",
    "Margot Robbie",
    "Gal Gadot",
    "Brie Larson",
    
    # MCU & Action Stars (26-50)
    "Tessa Thompson",
    "Danai Gurira",
    "Letitia Wright",
    "Lashana Lynch",
    "Jodie Turner Smith",
    "Rachel Weisz",
    "Emily Blunt",
    "Jessica Chastain",
    "Kristen Stewart",
    "Keira Knightley",
    "Kate Winslet",
    "Rachel McAdams",
    "Penelope Cruz",
    "Salma Hayek",
    "Eva Longoria",
    "Michelle Williams",
    "Rooney Mara",
    "Carey Mulligan",
    "Naomi Watts",
    "Reese Witherspoon",
    "Jennifer Aniston",
    "Kerry Washington",
    "Zoe Saldana",
    "Maggie Gyllenhaal",
    "Katie Holmes",
    
    # Legends (51-70)
    "Angela Lansbury",
    "Jodie Foster",
    "Glenn Close",
    "Sigourney Weaver",
    "Jamie Lee Curtis",
    "Laura Dern",
    "Frances McDormand",
    "Tilda Swinton",
    "Helen Mirren",
    "Judi Dench",
    "Emma Thompson",
    "Kate Hudson",
    "Drew Barrymore",
    "Cameron Diaz",
    "Kristen Wiig",
    "Maya Rudolph",
    "Melissa McCarthy",
    "Tiffany Haddish",
    "Awkwafina",
    "Ali Wong",
    
    # Black Excellence (71-75)
    "Regina Hall",
    "Queen Latifah",
    "Nia Long",
    "Gabrielle Union",
    "Sanaa Lathan",
    
    # European Stars (76-90)
    "Monica Bellucci",
    "Sophie Marceau",
    "Audrey Tautou",
    "Marion Cotillard",
    "Isabelle Huppert",
    "Juliette Binoche",
    "Diane Kruger",
    "Noomi Rapace",
    "Alicia Vikander",
    "Rebecca Hall",
    "Emily Mortimer",
    "Hayley Atwell",
    "Elizabeth Olsen",
    "Mary Elizabeth Winstead",
    "Dakota Johnson",
    
    # Rising Stars (91-100)
    "Kristen Bell",
    "Anna Kendrick",
    "Chloe Grace Moretz",
    "Elle Fanning",
    "Dakota Fanning",
    "Rachel Brosnahan",
    "Lily James",
    "Anya Taylor Joy",
    "Jurnee Smollett",
    "Keke Palmer",
    
    # Harry Potter / British (101-115)
    "Emma Watson",
    "Bonnie Wright",
    "Evanna Lynch",
    "Maggie Smith",
    "Helena Bonham Carter",
    "Anne Bancroft",
    "Shirley MacLaine",
    "Jane Fonda",
    "Diane Keaton",
    "Susan Sarandon",
    "Sally Field",
    "Michelle Pfeiffer",
    "Meg Ryan",
    "Gillian Anderson",
    "Winona Ryder",
    
    # Gen Z Rising (116-130)
    "Naomi Scott",
    "Lili Reinhart",
    "Camila Mendes",
    "Mindy Kaling",
    "America Ferrera",
    "Gina Rodriguez",
    "Stephanie Beatriz",
    "Ariana DeBose",
    "Vanessa Hudgens",
    "Zazie Beetz",
    "Riley Keough",
    "Thandiwe Newton",
    "Gugu Mbatha Raw",
    "Cynthia Erivo",
    "Phoebe Waller Bridge",
    
    # British (131-140)
    "Olivia Colman",
    "Vanessa Kirby",
    "Felicity Jones",
    "Gemma Chan",
    "Constance Wu",
    "Lucy Liu",
    "Maggie Cheung",
    "Zhang Ziyi",
    "Gong Li",
    "Michelle Yeoh",
    
    # Asian Cinema (141-150)
    "Fan Bingbing",
    "Tang Wei",
    "Jeon Do yeon",
    "Son Ye jin",
    "Bae Doona",
    "Jun Ji hyun",
    "Kim Tae ri",
    "Park So dam",
    "Rinko Kikuchi",
    "Hong Chau",
    
    # Bollywood (151-170)
    "Priyanka Chopra Jonas",
    "Deepika Padukone",
    "Alia Bhatt",
    "Kareena Kapoor Khan",
    "Katrina Kaif",
    "Anushka Sharma",
    "Vidya Balan",
    "Rani Mukerji",
    "Aishwarya Rai Bachchan",
    "Madhuri Dixit",
    "Taapsee Pannu",
    "Kangana Ranaut",
    "Yami Gautam",
    "Shraddha Kapoor",
    "Kiara Advani",
    "Sonam Kapoor",
    "Bipasha Basu",
    "Tabu",
    "Konkona Sen Sharma",
    "Sridevi",
    
    # Latina Stars (171-180)
    "Yalitza Aparicio",
    "Eiza Gonzalez",
    "Ana de Armas",
    "Melissa Barrera",
    "Kate del Castillo",
    "Cecilia Suarez",
    "Karena Lam",
    "Charo Santos Concio",
    "Bea Alonzo",
    "Angel Locsin",
    
    # New Generation (181-195)
    "Lily Collins",
    "Zoe Kravitz",
    "Halle Bailey",
    "Teyonah Parris",
    "Dominique Fishback",
    "Danielle Deadwyler",
    "Aunjanue Ellis Taylor",
    "DaVine Joy Randolph",
    "Rachel Zegler",
    "Jenna Ortega",
    "Florence Kasumba",
    "Sibongile Mlambo",
    "Thuso Mbedu",
    "Nomzamo Mbatha",
    "Mary J Blige",
    
    # Multi-Hyphenates (196-210)
    "Janelle Monae",
    "Tracee Ellis Ross",
    "Patricia Arquette",
    "Rosamund Pike",
    "Amanda Seyfried",
    "Michelle Rodriguez",
    "Karen Gillan",
    "Lena Headey",
    "Emilia Clarke",
    "Sophie Turner",
    "Maisie Williams",
    "Gwendoline Christie",
    "Natalie Dormer",
    "Bel Powley",
    "Thomasin McKenzie",
    
    # TV Crossovers (211-230)
    "Haley Lu Richardson",
    "Joey King",
    "Sydney Sweeney",
    "Alison Brie",
    "Betty Gilpin",
    "Lisa Kudrow",
    "Courteney Cox",
    "Mila Kunis",
    "Natalie Emmanuel",
    "Kelly Marie Tran",
    "Daisy Ridley",
    "Billie Lourd",
    "Laura Harrier",
    "Brenda Song",
    "Maggie Q",
    "Gina Carano",
    "Michelle Monaghan",
    "Jennifer Garner",
    "Hilary Swank",
    "Catherine Zeta Jones",
    
    # Action & International (231-250)
    "Taraji P Henson",  # duplicate but in original list
    "Octavia Spencer",  # duplicate but in original list
    "Stephanie Hsu",
    "Mary Elizabeth Mastrantonio",
    "Emily Ratajkowski",
    "Eva Green",
    "Paz Vega",
    "Carla Gugino",
    "Jennifer Connelly",
    "Famke Janssen",
    "Toni Collette",
    "Vera Farmiga",
    "Carice van Houten",
    "Morena Baccarin",
    "Carla Ortiz",
    "Kate Beckinsale",
    "Olga Kurylenko",
    "Gemma Arterton",
    "Naomie Harris",
    "Rosario Dawson"
]

print(f"Movie Stars Bank loaded: {len(MOVIE_STARS_BANK)} actresses")

# Quick access categories
OSCAR_WINNERS = MOVIE_STARS_BANK[0:25]
MCU_STARS = MOVIE_STARS_BANK[25:50]
LEGENDS = MOVIE_STARS_BANK[50:70]
BLACK_EXCELLENCE = MOVIE_STARS_BANK[70:75]
EUROPEAN = MOVIE_STARS_BANK[75:90]
BOLLYWOOD = MOVIE_STARS_BANK[150:170]
ASIAN_CINEMA = MOVIE_STARS_BANK[140:150]
GOT_STARS = [MOVIE_STARS_BANK[i] for i in [202, 203, 204, 205, 206, 207, 242]]
