# Movie Characters Bank - 250 Female Characters (NOT actresses)
# The actual cosplay targets for Nano Banana
# "The most chaotic cosplay generator on the planet"

MOVIE_CHARACTERS_BANK = [
    # STAR WARS (1-10)
    "Princess Leia Organa",
    "Rey",
    "Padmé Amidala",
    "Jyn Erso",
    "Rose Tico",
    "Qi'ra",
    "Ahsoka Tano",
    "Hera Syndulla",
    "Sabine Wren",
    "Maz Kanata",
    
    # MCU HEROES (11-30)
    "Black Widow Natasha Romanoff",
    "Scarlet Witch Wanda Maximoff",
    "Captain Marvel Carol Danvers",
    "Gamora",
    "Nebula",
    "Okoye",
    "Shuri",
    "Nakia",
    "Valkyrie",
    "Pepper Potts",
    "Jane Foster",
    "Hope van Dyne",
    "Janet van Dyne Wasp",
    "Mantis",
    "Maria Hill",
    "Peggy Carter",
    "Sharon Carter",
    "Christine Palmer",
    "MJ Michelle Jones Watson",
    "Gwen Stacy",
    
    # MCU SUPPORTING & X-MEN (31-45)
    "May Parker",
    "Jean Grey",
    "Storm Ororo Munroe",
    "Rogue",
    "Mystique Raven Darkholme",
    "Kitty Pryde",
    "Elektra Natchios",
    "Sue Storm",
    "Jessica Jones",
    "Trish Walker",
    "Karen Page",
    "Claire Temple",
    "Colleen Wing",
    "Domino Neena Thurman",
    "Vanessa Carlysle",
    
    # DC MOVIES (46-70)
    "Harley Quinn",
    "Wonder Woman Diana Prince",
    "Lois Lane",
    "Supergirl Kara Zor El",
    "Mera",
    "Catwoman Selina Kyle",
    "Talia al Ghul",
    "Rachel Dawes",
    "Vicki Vale",
    "Iris West",
    "Nora Allen",
    "Huntress Helena Bertinelli",
    "Black Canary Dinah Lance",
    "Batgirl Barbara Gordon",
    "Batwoman Kate Kane",
    "Enchantress June Moone",
    "Amanda Waller",
    "Poison Ivy Pamela Isley",
    "Zatanna Zatara",
    "Big Barda",
    "Hawkgirl Shayera Hol",
    "Raven",
    "Starfire Koriand r",
    "Killer Frost Caitlin Snow",
    "Cheetah Barbara Ann Minerva",
    
    # MCU VILLAINS & ASGARD (71-75)
    "Hela",
    "The Ancient One",
    "Proxima Midnight",
    "Lady Sif",
    "Frigga",
    
    # HARRY POTTER (76-85)
    "Hermione Granger",
    "Ginny Weasley",
    "Luna Lovegood",
    "Minerva McGonagall",
    "Molly Weasley",
    "Bellatrix Lestrange",
    "Nymphadora Tonks",
    "Cho Chang",
    "Fleur Delacour",
    "Dolores Umbridge",
    
    # YA DYSTOPIA (86-95)
    "Katniss Everdeen",
    "Primrose Everdeen",
    "Johanna Mason",
    "Effie Trinket",
    "Tris Prior",
    "Christina Divergent",
    "Tori Wu",
    "Hazel Grace Lancaster",
    "Clary Fray",
    "Isabelle Lightwood",
    
    # ACTION HEROINES (96-105)
    "Lisbeth Salander",
    "Clarice Starling",
    "Evelyn Salt",
    "Nikita",
    "Mathilda Leon",
    "Sarah Connor",
    "Ellen Ripley",
    "Newt Rebecca Jorden",
    "Furiosa",
    "Lorraine Broughton",
    
    # HORROR ICONS (106-115)
    "Lorraine Warren",
    "Sidney Prescott",
    "Gale Weathers",
    "Nancy Thompson",
    "Laurie Strode",
    "Carrie White",
    "Regan MacNeil",
    "Annie Wilkes",
    "Rose the Hat",
    "Selene Underworld",
    
    # VIDEO GAME MOVIES (116-125)
    "Sonja Underworld",
    "Alice Resident Evil",
    "Jill Valentine",
    "Claire Redfield",
    "Ada Wong",
    "Lara Croft",
    "Ramona Flowers",
    "Knives Chau",
    "Envy Adams",
    "Roxie Richter",
    
    # ADVENTURE & FRANCHISE (126-145)
    "Elizabeth Swann",
    "Tia Dalma",
    "Angelica Teach",
    "Neytiri",
    "Ronal",
    "Mo at",
    "Letty Ortiz",
    "Mia Toretto",
    "Ramsey Fast and Furious",
    "Cipher",
    "Cheedo the Fragile",
    "Miss Giddy",
    "Shoshanna Dreyfus",
    "Bridget von Hammersmark",
    "The Bride Beatrix Kiddo",
    "O Ren Ishii",
    "Gogo Yubari",
    "Vernita Green",
    "Elle Driver",
    "Trinity",
    
    # SCI-FI ICONS (146-150)
    "Niobe",
    "Persephone Matrix",
    "The Oracle Matrix",
    "Leeloo",
    "Diva Plavalaguna",
    
    # DISNEY PRINCESSES (151-170)
    "Princess Jasmine",
    "Belle",
    "Ariel",
    "Snow White",
    "Cinderella",
    "Aurora Sleeping Beauty",
    "Pocahontas",
    "Mulan",
    "Tiana",
    "Rapunzel",
    "Merida",
    "Moana",
    "Vanellope von Schweetz",
    "Elsa",
    "Anna",
    "Mirabel Madrigal",
    "Isabela Madrigal",
    "Luisa Madrigal",
    "Dolores Madrigal",
    "Esmeralda",
    
    # DISNEY HEROINES (171-190)
    "Megara",
    "Jane Porter",
    "Nani Pelekai",
    "Lilo Pelekai",
    "Kida Nedakh",
    "Helen Parr Elastigirl",
    "Violet Parr",
    "Edna Mode",
    "Jessie Toy Story",
    "Bo Peep",
    "Joy Inside Out",
    "Sadness Inside Out",
    "Disgust Inside Out",
    "Riley Andersen",
    "Colette Tatou",
    "EVE from Wall E",
    "Princess Atta",
    "Dot A Bug's Life",
    "Judy Hopps",
    "Officer Fangmeyer",
    
    # DREAMWORKS & ANIMATION (191-200)
    "Princess Fiona ogre form",
    "Princess Fiona human form",
    "Tigress Kung Fu Panda",
    "Viper Kung Fu Panda",
    "Astrid Hofferson",
    "Ruffnut Thorston",
    "Valka",
    "Heather How to Train Your Dragon",
    "Coraline Jones",
    "Miss Spink",
    
    # BARBIE (201-209)
    "Barbie Stereotypical Barbie",
    "Gloria Barbie movie",
    "President Barbie",
    "Weird Barbie",
    "Mermaid Barbie",
    "Doctor Barbie",
    "Writer Barbie",
    "Sasha Barbie movie",
    "Ruth Handler character",
    
    # WONDER WOMAN & BLACK PANTHER (210-216)
    "Antiope Wonder Woman",
    "Hippolyta Wonder Woman",
    "Etta Candy",
    "Queen Ramonda",
    "Ayo",
    "Riri Williams",
    "Namora",
    
    # CLASSIC CINEMA ICONS (217-235)
    "Holly Golightly",
    "Vivian Ward",
    "Erin Brockovich",
    "Thelma Dickinson",
    "Louise Sawyer",
    "Mia Wallace",
    "Jackie Brown",
    "Foxy Brown",
    "Coffy",
    "Maria von Trapp",
    "Mary Poppins",
    "Amélie Poulain",
    "Mia Thermopolis",
    "Queen Clarisse Renaldi",
    "Elle Woods",
    "Vivian Kensington",
    "Juno MacGuff",
    "Olive Penderghast",
    "Lara Jean Covey",
    
    # MODERN ICONS (236-250)
    "Rachel Chu",
    "Astrid Leong",
    "Donna Sheridan",
    "Sophie Sheridan",
    "Mia Dolan",
    "Nina Sayers",
    "Jackie Kennedy from Jackie",
    "Molly Bloom",
    "Ally Maine",
    "Lisa Fremont",
    "Marion Crane",
    "Norma Desmond",
    "Dorothy Gale",
    "Glinda the Good Witch",
    "Wicked Witch of the West"
]

print(f"Movie Characters Bank loaded: {len(MOVIE_CHARACTERS_BANK)} characters")

# Quick access by franchise
STAR_WARS = MOVIE_CHARACTERS_BANK[0:10]
MCU_HEROES = MOVIE_CHARACTERS_BANK[10:30]
DC_MOVIES = MOVIE_CHARACTERS_BANK[45:70]
HARRY_POTTER = MOVIE_CHARACTERS_BANK[75:85]
HUNGER_GAMES = MOVIE_CHARACTERS_BANK[85:89]
HORROR_ICONS = MOVIE_CHARACTERS_BANK[105:115]
DISNEY_PRINCESSES = MOVIE_CHARACTERS_BANK[150:170]
PIXAR = MOVIE_CHARACTERS_BANK[175:190]
BARBIE = MOVIE_CHARACTERS_BANK[200:209]
KILL_BILL = [MOVIE_CHARACTERS_BANK[i] for i in range(139, 144)]
MATRIX = [MOVIE_CHARACTERS_BANK[i] for i in range(144, 148)]
